from System.Collections.Generic import *

import math
import clr

clr.AddReference("System.Drawing")
from System import String
from System.Drawing import Color


# SpaceClaim.Api.V18 types:
from SpaceClaim.Api.V18 import AcisExportOptions
from SpaceClaim.Api.V18 import AcisImportOptions
from SpaceClaim.Api.V18 import AcisUnits
from SpaceClaim.Api.V18 import AcisVersion
from SpaceClaim.Api.V18 import AdvancedPropertyDisplay
from SpaceClaim.Api.V18 import AlignCondition
from SpaceClaim.Api.V18 import AlignedViewAspect
from SpaceClaim.Api.V18 import AnalysisAspect
from SpaceClaim.Api.V18 import AnalysisOptions
from SpaceClaim.Api.V18 import AnalysisType
from SpaceClaim.Api.V18 import AnchorCondition
from SpaceClaim.Api.V18 import AngleConverter
from SpaceClaim.Api.V18 import AngleUnit
from SpaceClaim.Api.V18 import Animation
from SpaceClaim.Api.V18.Animation import Cancel
from SpaceClaim.Api.V18.Animation import Start
from SpaceClaim.Api.V18.Animation import Stop
from SpaceClaim.Api.V18 import AnimationCompletedEventArgs
from SpaceClaim.Api.V18 import AnimationResult
from SpaceClaim.Api.V18 import Animator
from SpaceClaim.Api.V18 import AnnotationSpace
from SpaceClaim.Api.V18 import Api
from SpaceClaim.Api.V18.Api import AttachToSession
from SpaceClaim.Api.V18.Api import Initialize
from SpaceClaim.Api.V18.Api import IsKeptAlive
from SpaceClaim.Api.V18.Api import KeepAlive
from SpaceClaim.Api.V18 import AppearanceState
from SpaceClaim.Api.V18 import Application
from SpaceClaim.Api.V18 import ApplicationVersion
from SpaceClaim.Api.V18 import ApplicationWindowState
from SpaceClaim.Api.V18 import ApplyLoop
from SpaceClaim.Api.V18 import AttachToFace
from SpaceClaim.Api.V18 import AttachToPlane
from SpaceClaim.Api.V18 import AutoKeepAliveBlock
from SpaceClaim.Api.V18 import AxialBend
from SpaceClaim.Api.V18 import AxisType
from SpaceClaim.Api.V18 import Barcode
from SpaceClaim.Api.V18 import BarcodeCodePage
from SpaceClaim.Api.V18 import BarcodeProperties
from SpaceClaim.Api.V18 import BarcodeToolHandler
from SpaceClaim.Api.V18 import BarcodeType
from SpaceClaim.Api.V18 import Base
from SpaceClaim.Api.V18 import Bead
from SpaceClaim.Api.V18 import Beam
from SpaceClaim.Api.V18 import BeamType
from SpaceClaim.Api.V18 import Bend
from SpaceClaim.Api.V18 import BendOptions
from SpaceClaim.Api.V18 import BendSpecification
from SpaceClaim.Api.V18 import BendStep
from SpaceClaim.Api.V18 import BendTooling
from SpaceClaim.Api.V18 import BodyStyle
from SpaceClaim.Api.V18 import BossForm
from SpaceClaim.Api.V18 import BridgeForm
from SpaceClaim.Api.V18 import CADImportParameterType
from SpaceClaim.Api.V18 import Callout
from SpaceClaim.Api.V18 import Camera
from SpaceClaim.Api.V18 import CameraType
from SpaceClaim.Api.V18 import CancelStatus
from SpaceClaim.Api.V18 import CardGuideForm
from SpaceClaim.Api.V18 import CatiaExportOptions
from SpaceClaim.Api.V18 import CatiaImportOptions
from SpaceClaim.Api.V18 import CatiaVersion
from SpaceClaim.Api.V18 import CheckDigitType
from SpaceClaim.Api.V18 import CircularRelief
from SpaceClaim.Api.V18 import CircularReliefSetting
from SpaceClaim.Api.V18 import CircularSense
from SpaceClaim.Api.V18 import ClosedHem
from SpaceClaim.Api.V18 import ColorRenderingBatch
from SpaceClaim.Api.V18 import ComboBoxState
from SpaceClaim.Api.V18 import Command
from SpaceClaim.Api.V18 import CommandException
from SpaceClaim.Api.V18 import CommandExecutingEventArgs
from SpaceClaim.Api.V18 import CommandFilter
from SpaceClaim.Api.V18 import CommandTextChangedEventArgs
from SpaceClaim.Api.V18 import Component
from SpaceClaim.Api.V18 import ConicalBend
from SpaceClaim.Api.V18 import ConnectionTable
from SpaceClaim.Api.V18 import ContextMenu
from SpaceClaim.Api.V18 import ContextMenuEventArgs
from SpaceClaim.Api.V18 import ContextMenuId
from SpaceClaim.Api.V18 import ContextSubMenu
from SpaceClaim.Api.V18 import ControlState
from SpaceClaim.Api.V18 import CoordinateAxis
from SpaceClaim.Api.V18 import CoordinateSystem
from SpaceClaim.Api.V18 import CoreProperties
from SpaceClaim.Api.V18 import CornerRelief
from SpaceClaim.Api.V18 import CornerReliefPlacement
from SpaceClaim.Api.V18 import CornerReliefPosition
from SpaceClaim.Api.V18 import CornerReliefSetting
from SpaceClaim.Api.V18 import CornerReliefType
from SpaceClaim.Api.V18 import CountCallout
from SpaceClaim.Api.V18 import CountersinkForm
from SpaceClaim.Api.V18 import CrossBreak
from SpaceClaim.Api.V18 import CupForm
from SpaceClaim.Api.V18 import CurvePoint
from SpaceClaim.Api.V18 import CustomDisplayName
from SpaceClaim.Api.V18 import CustomForm
from SpaceClaim.Api.V18 import CustomFormOptions
from SpaceClaim.Api.V18 import CustomObject
from SpaceClaim.Api.V18 import CustomPartProperty
from SpaceClaim.Api.V18 import CustomPartPropertyDictionary
from SpaceClaim.Api.V18 import CustomProperty
from SpaceClaim.Api.V18 import CustomPropertyDictionary
from SpaceClaim.Api.V18 import CustomWrapper
from SpaceClaim.Api.V18 import CutoutFacePattern
from SpaceClaim.Api.V18 import CutoutForm
from SpaceClaim.Api.V18 import CutoutFormPattern
from SpaceClaim.Api.V18 import CylindricalBend
from SpaceClaim.Api.V18 import DataMatrixBarcodeProperties
from SpaceClaim.Api.V18 import DataMatrixBarcodeSize
from SpaceClaim.Api.V18 import DatumFeature
from SpaceClaim.Api.V18 import DatumFeatureCallout
from SpaceClaim.Api.V18 import DatumFeatureSymbol
from SpaceClaim.Api.V18 import DatumLine
from SpaceClaim.Api.V18 import DatumPlane
from SpaceClaim.Api.V18 import DatumPoint
from SpaceClaim.Api.V18 import DatumReference
from SpaceClaim.Api.V18 import DecimalViewScale
from SpaceClaim.Api.V18 import DefaultVisibility
from SpaceClaim.Api.V18 import DerivedPlane
from SpaceClaim.Api.V18 import DerivedPoint
from SpaceClaim.Api.V18 import DerivedViewAspect
from SpaceClaim.Api.V18 import DesignAxis
from SpaceClaim.Api.V18 import DesignBody
from SpaceClaim.Api.V18 import DesignBodyAspect
from SpaceClaim.Api.V18 import DesignCurve
from SpaceClaim.Api.V18 import DesignCurveGroup
from SpaceClaim.Api.V18 import DesignCurveGroupType
from SpaceClaim.Api.V18 import DesignEdge
from SpaceClaim.Api.V18 import DesignFace
from SpaceClaim.Api.V18 import DesignMesh
from SpaceClaim.Api.V18 import DesignMeshItem
from SpaceClaim.Api.V18 import DesignMeshLoop
from SpaceClaim.Api.V18 import DesignMeshRegion
from SpaceClaim.Api.V18 import DesignMeshTopology
from SpaceClaim.Api.V18 import DesignWindowOptions
from SpaceClaim.Api.V18 import DetailViewAspect
from SpaceClaim.Api.V18 import DiagonalRelief
from SpaceClaim.Api.V18 import DiagonalReliefSetting
from SpaceClaim.Api.V18 import DiametericReliefSetting
from SpaceClaim.Api.V18 import DiametricRelief
from SpaceClaim.Api.V18 import DimensionCallout
from SpaceClaim.Api.V18 import DimensionType
from SpaceClaim.Api.V18 import DimpleForm
from SpaceClaim.Api.V18 import DisplayImage
from SpaceClaim.Api.V18 import Disposable
from SpaceClaim.Api.V18 import DockLocation
from SpaceClaim.Api.V18 import DocObject
from SpaceClaim.Api.V18 import Document
from SpaceClaim.Api.V18 import DocumentChangedEventArgs
from SpaceClaim.Api.V18 import DocumentMaterial
from SpaceClaim.Api.V18 import DocumentMaterialDictionary
from SpaceClaim.Api.V18 import DoubleConverter
from SpaceClaim.Api.V18 import DraftingFont
from SpaceClaim.Api.V18 import DrawingSheet
from SpaceClaim.Api.V18 import DrawingSheetBatch
from SpaceClaim.Api.V18 import DrawingSheetContents
from SpaceClaim.Api.V18 import DrawingSheetWindowExportFormat
from SpaceClaim.Api.V18 import DrawingView
from SpaceClaim.Api.V18 import DrawingViewAspect
from SpaceClaim.Api.V18 import DrawingViewBoundary
from SpaceClaim.Api.V18 import DrawingViewColorRendering
from SpaceClaim.Api.V18 import DrawingViewDisplayName
from SpaceClaim.Api.V18 import DrawingViewRendering
from SpaceClaim.Api.V18 import DrawingViewScale
from SpaceClaim.Api.V18 import DrawingViewSection
from SpaceClaim.Api.V18 import DrawingViewSectionType
from SpaceClaim.Api.V18 import DrawingViewStyle
from SpaceClaim.Api.V18 import DrawingWindowOptions
from SpaceClaim.Api.V18 import EmbeddedWindowHandler
from SpaceClaim.Api.V18 import EnclosureAspect
from SpaceClaim.Api.V18 import ExecutionContext
from SpaceClaim.Api.V18 import ExportOptions
from SpaceClaim.Api.V18 import ExtrusionForm
from SpaceClaim.Api.V18 import FeatureControlFrame
from SpaceClaim.Api.V18 import FileLoadResolver
from SpaceClaim.Api.V18 import FileOpenHandler
from SpaceClaim.Api.V18 import FileSaveHandler
from SpaceClaim.Api.V18 import FilledReliefSetting
from SpaceClaim.Api.V18 import FlatGusset
from SpaceClaim.Api.V18 import FlatPatternAspect
from SpaceClaim.Api.V18 import FlatPatternFormState
from SpaceClaim.Api.V18 import FourWaySplit
from SpaceClaim.Api.V18 import FractionalViewScale
from SpaceClaim.Api.V18 import FrameCondition
from SpaceClaim.Api.V18 import GalleryState
from SpaceClaim.Api.V18 import GearCondition
from SpaceClaim.Api.V18 import GeometricCharacteristic
from SpaceClaim.Api.V18 import GeometricCondition
from SpaceClaim.Api.V18 import GeometricToleranceCallout
from SpaceClaim.Api.V18 import GridSettings
from SpaceClaim.Api.V18 import Group
from SpaceClaim.Api.V18 import Gusset
from SpaceClaim.Api.V18 import GussetSite
from SpaceClaim.Api.V18 import GussetStyle
from SpaceClaim.Api.V18 import Handle
from SpaceClaim.Api.V18 import HatchBoundary
from SpaceClaim.Api.V18 import HatchLine
from SpaceClaim.Api.V18 import HatchLoop
from SpaceClaim.Api.V18 import HatchPattern
from SpaceClaim.Api.V18 import HeavyweightFacePattern
from SpaceClaim.Api.V18 import HeavyweightFormPattern
from SpaceClaim.Api.V18 import HemBend
from SpaceClaim.Api.V18 import HemStyle
from SpaceClaim.Api.V18 import Hole
from SpaceClaim.Api.V18 import HoleCreationInfo
from SpaceClaim.Api.V18 import HoleDepthMeasurementType
from SpaceClaim.Api.V18 import HoleFit
from SpaceClaim.Api.V18 import HorizontalAlignment
from SpaceClaim.Api.V18 import IdentifyHoleOptions
from SpaceClaim.Api.V18 import Image
from SpaceClaim.Api.V18 import ImageAttachment
from SpaceClaim.Api.V18 import ImageLock
from SpaceClaim.Api.V18 import ImperialLengthUnit
from SpaceClaim.Api.V18 import ImperialMassUnit
from SpaceClaim.Api.V18 import ImperialUnits
from SpaceClaim.Api.V18 import ImportCompleteness
from SpaceClaim.Api.V18 import ImportOptions
from SpaceClaim.Api.V18 import Indicator
from SpaceClaim.Api.V18 import Instance
from SpaceClaim.Api.V18 import InteractionContext
from SpaceClaim.Api.V18 import InteractionMode
from SpaceClaim.Api.V18 import InternalErrorException
from SpaceClaim.Api.V18 import JoggleAngles
from SpaceClaim.Api.V18 import JoggleBend
from SpaceClaim.Api.V18 import KeepAliveObject
from SpaceClaim.Api.V18 import KeyShotSurfaceMaterial
from SpaceClaim.Api.V18 import KnockoutForm
from SpaceClaim.Api.V18 import LaserEdgeRelief
from SpaceClaim.Api.V18 import LaserEdgeReliefSetting
from SpaceClaim.Api.V18 import LaserSymmetricRelief
from SpaceClaim.Api.V18 import LaserSymmetricReliefSetting
from SpaceClaim.Api.V18 import Layer
from SpaceClaim.Api.V18 import LayoutGrid
from SpaceClaim.Api.V18 import LayoutGridDisplay
from SpaceClaim.Api.V18 import LeftRightSplit
from SpaceClaim.Api.V18 import LengthConverter
from SpaceClaim.Api.V18 import Lettering
from SpaceClaim.Api.V18 import LibraryMaterial
from SpaceClaim.Api.V18 import LibraryMaterialDictionary
from SpaceClaim.Api.V18 import LightweightCustomObject
from SpaceClaim.Api.V18 import LightweightCustomWrapper
from SpaceClaim.Api.V18 import LightweightFacePattern
from SpaceClaim.Api.V18 import LightweightFormPattern
from SpaceClaim.Api.V18 import LightweightNote
from SpaceClaim.Api.V18 import LineStyle
from SpaceClaim.Api.V18 import LineWeight
from SpaceClaim.Api.V18 import LineWeightType
from SpaceClaim.Api.V18 import LocationPoint
from SpaceClaim.Api.V18 import LockedException
from SpaceClaim.Api.V18 import LongDisplayName
from SpaceClaim.Api.V18 import LouverForm
from SpaceClaim.Api.V18 import ManualKeepAliveBlock
from SpaceClaim.Api.V18 import Marker
from SpaceClaim.Api.V18 import MassProperties
from SpaceClaim.Api.V18 import Material
from SpaceClaim.Api.V18 import MaterialCondition
from SpaceClaim.Api.V18 import MaterialProperty
from SpaceClaim.Api.V18 import MaterialPropertyDictionary
from SpaceClaim.Api.V18 import MaterialPropertyId
from SpaceClaim.Api.V18 import MatingCondition
from SpaceClaim.Api.V18 import MeasurementUnit
from SpaceClaim.Api.V18 import MeshColorMap
from SpaceClaim.Api.V18 import MetricLengthUnit
from SpaceClaim.Api.V18 import MetricMassUnit
from SpaceClaim.Api.V18 import MetricUnits
from SpaceClaim.Api.V18 import MidSurfaceAspect
from SpaceClaim.Api.V18 import MixedImportResolution
from SpaceClaim.Api.V18 import ModifyLockedDocumentBlock
from SpaceClaim.Api.V18 import NativeCommand
from SpaceClaim.Api.V18 import Note
from SpaceClaim.Api.V18 import NoteCurvature
from SpaceClaim.Api.V18 import ObjExportOptions
from SpaceClaim.Api.V18 import ObjImportOptions
from SpaceClaim.Api.V18 import OblongRelief
from SpaceClaim.Api.V18 import OblongReliefSetting
from SpaceClaim.Api.V18 import OpenHem
from SpaceClaim.Api.V18 import Options
from SpaceClaim.Api.V18 import OptionsPage
from SpaceClaim.Api.V18 import OptionsPageSection
from SpaceClaim.Api.V18 import OrientCondition
from SpaceClaim.Api.V18 import Panel
from SpaceClaim.Api.V18 import PanelTab
from SpaceClaim.Api.V18 import ParasolidExportOptions
from SpaceClaim.Api.V18 import ParasolidVersion
from SpaceClaim.Api.V18 import Part
from SpaceClaim.Api.V18 import PartAspect
from SpaceClaim.Api.V18 import PartAspectGeneral
from SpaceClaim.Api.V18 import PartExportFormat
from SpaceClaim.Api.V18 import PartType
from SpaceClaim.Api.V18 import PartWindowExportFormat
from SpaceClaim.Api.V18 import PickboxObjectType
from SpaceClaim.Api.V18 import PixelDepth
from SpaceClaim.Api.V18 import PointType
from SpaceClaim.Api.V18 import ProgressTracker
from SpaceClaim.Api.V18 import PropertiesChangedEventArgs
from SpaceClaim.Api.V18 import PropertyDisplay
from SpaceClaim.Api.V18 import QRCodeBarcodeProperties
from SpaceClaim.Api.V18 import QRCodeErrorCorrectionLevel
from SpaceClaim.Api.V18 import RadialMenu
from SpaceClaim.Api.V18 import RadialMenuEventArgs
from SpaceClaim.Api.V18 import RaisedCountersinkForm
from SpaceClaim.Api.V18 import ReadOnlyPropertyDisplay
from SpaceClaim.Api.V18 import Readout
from SpaceClaim.Api.V18 import ReadoutField
from SpaceClaim.Api.V18 import RectangularRelief
from SpaceClaim.Api.V18 import RectangularReliefSetting
from SpaceClaim.Api.V18 import RegularGusset
from SpaceClaim.Api.V18 import RemoteObject
from SpaceClaim.Api.V18 import RenderingBatch
from SpaceClaim.Api.V18 import RenderQuality
from SpaceClaim.Api.V18 import ReplayParameter
from SpaceClaim.Api.V18 import RigidCondition
from SpaceClaim.Api.V18 import RollDirection
from SpaceClaim.Api.V18 import RolledHem
from SpaceClaim.Api.V18 import RollEventType
from SpaceClaim.Api.V18 import RoundedLouverForm
from SpaceClaim.Api.V18 import RoundGusset
from SpaceClaim.Api.V18 import SaveDocumentEventArgs
from SpaceClaim.Api.V18 import SaveDocumentOriginator
from SpaceClaim.Api.V18 import Section
from SpaceClaim.Api.V18 import SectionAnchor
from SpaceClaim.Api.V18 import SectionCurve
from SpaceClaim.Api.V18 import SectionProperties
from SpaceClaim.Api.V18 import SelectionFilterType
from SpaceClaim.Api.V18 import SelectionOrder
from SpaceClaim.Api.V18 import SelectionResult
from SpaceClaim.Api.V18 import Session
from SpaceClaim.Api.V18 import SessionChangedEventArgs
from SpaceClaim.Api.V18 import SessionRolledEventArgs
from SpaceClaim.Api.V18 import ShareTopology
from SpaceClaim.Api.V18 import SheetMetalAspect
from SpaceClaim.Api.V18 import SheetMetalBendHandler
from SpaceClaim.Api.V18 import SheetMetalBendToolMode
from SpaceClaim.Api.V18 import SheetMetalCorner
from SpaceClaim.Api.V18 import SheetMetalFeature
from SpaceClaim.Api.V18 import SheetMetalForm
from SpaceClaim.Api.V18 import SheetMetalFormHandler
from SpaceClaim.Api.V18 import SheetMetalFormPreview
from SpaceClaim.Api.V18 import SheetMetalOptions
from SpaceClaim.Api.V18 import ShortDisplayName
from SpaceClaim.Api.V18 import SimplePropertyDisplay
from SpaceClaim.Api.V18 import SliderState
from SpaceClaim.Api.V18 import SmoothRelief
from SpaceClaim.Api.V18 import SmoothReliefSetting
from SpaceClaim.Api.V18 import Spacing
from SpaceClaim.Api.V18 import SpecialChar
from SpaceClaim.Api.V18 import SpinBoxState
from SpaceClaim.Api.V18 import SpotWeld
from SpaceClaim.Api.V18 import SpotWeldJoint
from SpaceClaim.Api.V18 import SquareRelief
from SpaceClaim.Api.V18 import SquareReliefSetting
from SpaceClaim.Api.V18 import StartupOptions
from SpaceClaim.Api.V18 import StatusMessageType
from SpaceClaim.Api.V18 import StepExportOptions
from SpaceClaim.Api.V18 import StlExportFormat
from SpaceClaim.Api.V18 import StlExportOptions
from SpaceClaim.Api.V18 import StlFileGranularity
from SpaceClaim.Api.V18 import StlImportOptions
from SpaceClaim.Api.V18 import StlImportType
from SpaceClaim.Api.V18 import SurfaceFinish
from SpaceClaim.Api.V18 import SurfaceFinishParameter
from SpaceClaim.Api.V18 import SurfaceFinishParameterType
from SpaceClaim.Api.V18 import SurfaceFinishType
from SpaceClaim.Api.V18 import SurfaceMaterial
from SpaceClaim.Api.V18 import Symbol
from SpaceClaim.Api.V18 import SymbolInsert
from SpaceClaim.Api.V18 import SymbolSize
from SpaceClaim.Api.V18 import SymbolSizeType
from SpaceClaim.Api.V18 import Tab
from SpaceClaim.Api.V18 import Table
from SpaceClaim.Api.V18 import TableCell
from SpaceClaim.Api.V18 import TableCellChangedEventArgs
from SpaceClaim.Api.V18 import TableColumn
from SpaceClaim.Api.V18 import TableRow
from SpaceClaim.Api.V18 import TangentCondition
from SpaceClaim.Api.V18 import Task
from SpaceClaim.Api.V18 import TeardropHem
from SpaceClaim.Api.V18 import TextCallout
from SpaceClaim.Api.V18 import TextFit
from SpaceClaim.Api.V18 import TextInfo
from SpaceClaim.Api.V18 import TextureSurfaceMaterial
from SpaceClaim.Api.V18 import ThreadPunchForm
from SpaceClaim.Api.V18 import ToleranceFormat
from SpaceClaim.Api.V18 import Tool
from SpaceClaim.Api.V18 import ToolGuideLayout
from SpaceClaim.Api.V18 import ToolGuidePosition
from SpaceClaim.Api.V18 import TopBottomSplit
from SpaceClaim.Api.V18 import TriangularRelief
from SpaceClaim.Api.V18 import TriangularReliefSetting
from SpaceClaim.Api.V18 import Units
from SpaceClaim.Api.V18 import UnitsSystem
from SpaceClaim.Api.V18 import UnitsSystemType
from SpaceClaim.Api.V18 import UnknownGusset
from SpaceClaim.Api.V18 import UpdateFrequency
from SpaceClaim.Api.V18 import UpdateState
from SpaceClaim.Api.V18 import ValueConverter
from SpaceClaim.Api.V18 import ValueDefinition
from SpaceClaim.Api.V18 import ValueType
from SpaceClaim.Api.V18 import VerticalAlignment
from SpaceClaim.Api.V18 import VideoCapture
from SpaceClaim.Api.V18 import VideoCodec
from SpaceClaim.Api.V18 import ViewProjection
from SpaceClaim.Api.V18 import VolumeExtractionAspect
from SpaceClaim.Api.V18 import WatertightReliefSetting
from SpaceClaim.Api.V18 import Window
from SpaceClaim.Api.V18 import WindowExportFormat
from SpaceClaim.Api.V18 import WindowSplit
from SpaceClaim.Api.V18 import WindowTab
from SpaceClaim.Api.V18 import WindowTabHandler
from SpaceClaim.Api.V18 import WireCurve
from SpaceClaim.Api.V18 import WireCurveConnection
from SpaceClaim.Api.V18 import WireCurvePoint
from SpaceClaim.Api.V18 import WorkbenchImportOptions
from SpaceClaim.Api.V18 import WorldOrientation
from SpaceClaim.Api.V18 import WriteBlock
from SpaceClaim.Api.V18.WriteBlock import AppendTask
from SpaceClaim.Api.V18.WriteBlock import ExecuteTask
from SpaceClaim.Api.V18.Modeler import Body
from SpaceClaim.Api.V18.Modeler import BodyIntersection
from SpaceClaim.Api.V18.Modeler import BodyRendering
from SpaceClaim.Api.V18.Modeler import BodySaveFormat
from SpaceClaim.Api.V18.Modeler import Edge
from SpaceClaim.Api.V18.Modeler import EdgeRendering
from SpaceClaim.Api.V18.Modeler import EdgeRound
from SpaceClaim.Api.V18.Modeler import Face
from SpaceClaim.Api.V18.Modeler import FaceGeometry
from SpaceClaim.Api.V18.Modeler import FaceRendering
from SpaceClaim.Api.V18.Modeler import Facet
from SpaceClaim.Api.V18.Modeler import FaceTessellation
from SpaceClaim.Api.V18.Modeler import Fin
from SpaceClaim.Api.V18.Modeler import FixedRadiusRound
from SpaceClaim.Api.V18.Modeler import ForeignBody
from SpaceClaim.Api.V18.Modeler import ForeignEdge
from SpaceClaim.Api.V18.Modeler import ForeignFace
from SpaceClaim.Api.V18.Modeler import ForeignFin
from SpaceClaim.Api.V18.Modeler import ForeignLoop
from SpaceClaim.Api.V18.Modeler import ForeignLump
from SpaceClaim.Api.V18.Modeler import ForeignObject
from SpaceClaim.Api.V18.Modeler import ForeignShell
from SpaceClaim.Api.V18.Modeler import ForeignTopology
from SpaceClaim.Api.V18.Modeler import ForeignVertex
from SpaceClaim.Api.V18.Modeler import Loop
from SpaceClaim.Api.V18.Modeler import Mesh
from SpaceClaim.Api.V18.Modeler import MeshEdge
from SpaceClaim.Api.V18.Modeler import MeshFace
from SpaceClaim.Api.V18.Modeler import MeshTopology
from SpaceClaim.Api.V18.Modeler import MeshVertex
from SpaceClaim.Api.V18.Modeler import ProjectionExtent
from SpaceClaim.Api.V18.Modeler import ProjectionOptions
from SpaceClaim.Api.V18.Modeler import RadiusPoint
from SpaceClaim.Api.V18.Modeler import RepairAction
from SpaceClaim.Api.V18.Modeler import TessellationOptions
from SpaceClaim.Api.V18.Modeler import Topology
from SpaceClaim.Api.V18.Modeler import Tracker
from SpaceClaim.Api.V18.Modeler import TransformedBody
from SpaceClaim.Api.V18.Modeler import VariableRadiusRound
from SpaceClaim.Api.V18.Modeler import Vertex
from SpaceClaim.Api.V18.Display import ArrowPrimitive
from SpaceClaim.Api.V18.Display import CurvePrimitive
from SpaceClaim.Api.V18.Display import DisplayRange
from SpaceClaim.Api.V18.Display import Graphic
from SpaceClaim.Api.V18.Display import GraphicStyle
from SpaceClaim.Api.V18.Display import LinePrimitive
from SpaceClaim.Api.V18.Display import MeshEdgeDisplay
from SpaceClaim.Api.V18.Display import MeshPrimitive
from SpaceClaim.Api.V18.Display import NotePrimitive
from SpaceClaim.Api.V18.Display import PointPrimitive
from SpaceClaim.Api.V18.Display import PolylinePrimitive
from SpaceClaim.Api.V18.Display import PolypointPrimitive
from SpaceClaim.Api.V18.Display import PositionColored
from SpaceClaim.Api.V18.Display import PositionNormal
from SpaceClaim.Api.V18.Display import PositionNormalTextured
from SpaceClaim.Api.V18.Display import Primitive
from SpaceClaim.Api.V18.Display import ShowWhen
from SpaceClaim.Api.V18.Display import TextPadding
from SpaceClaim.Api.V18.Display import TextPrimitive
from SpaceClaim.Api.V18.Geometry import Accuracy
from SpaceClaim.Api.V18.Geometry.Accuracy import AngleIsNegative
from SpaceClaim.Api.V18.Geometry.Accuracy import AngleIsPositive
from SpaceClaim.Api.V18.Geometry.Accuracy import AngleIsZero
from SpaceClaim.Api.V18.Geometry.Accuracy import CompareAngles
from SpaceClaim.Api.V18.Geometry.Accuracy import CompareAreas
from SpaceClaim.Api.V18.Geometry.Accuracy import CompareLengths
from SpaceClaim.Api.V18.Geometry.Accuracy import CompareVolumes
from SpaceClaim.Api.V18.Geometry.Accuracy import EqualAngles
from SpaceClaim.Api.V18.Geometry.Accuracy import EqualAreas
from SpaceClaim.Api.V18.Geometry.Accuracy import EqualLengths
from SpaceClaim.Api.V18.Geometry.Accuracy import EqualVolumes
from SpaceClaim.Api.V18.Geometry.Accuracy import LengthIsNegative
from SpaceClaim.Api.V18.Geometry.Accuracy import LengthIsPositive
from SpaceClaim.Api.V18.Geometry.Accuracy import LengthIsZero
from SpaceClaim.Api.V18.Geometry import ArrowProfile
from SpaceClaim.Api.V18.Geometry import Box
from SpaceClaim.Api.V18.Geometry import BoxUV
from SpaceClaim.Api.V18.Geometry import Circle
from SpaceClaim.Api.V18.Geometry import CircleProfile
from SpaceClaim.Api.V18.Geometry import Collision
from SpaceClaim.Api.V18.Geometry import Cone
from SpaceClaim.Api.V18.Geometry import ControlPoint
from SpaceClaim.Api.V18.Geometry import ControlPointUV
from SpaceClaim.Api.V18.Geometry import Curve
from SpaceClaim.Api.V18.Geometry import CurveEvaluation
from SpaceClaim.Api.V18.Geometry import CurveEvaluationUV
from SpaceClaim.Api.V18.Geometry import CurveParam
from SpaceClaim.Api.V18.Geometry import CurveSegment
from SpaceClaim.Api.V18.Geometry import Cylinder
from SpaceClaim.Api.V18.Geometry import Direction
from SpaceClaim.Api.V18.Geometry import DirectionUV
from SpaceClaim.Api.V18.Geometry import Ellipse
from SpaceClaim.Api.V18.Geometry import FitMethod
from SpaceClaim.Api.V18.Geometry import Frame
from SpaceClaim.Api.V18.Geometry import Geometry
from SpaceClaim.Api.V18.Geometry import Helix
from SpaceClaim.Api.V18.Geometry import Interval
from SpaceClaim.Api.V18.Geometry import Knot
from SpaceClaim.Api.V18.Geometry import Line
from SpaceClaim.Api.V18.Geometry import LineSegment
from SpaceClaim.Api.V18.Geometry import Matrix
from SpaceClaim.Api.V18.Geometry import NurbsCurve
from SpaceClaim.Api.V18.Geometry import NurbsCurveUV
from SpaceClaim.Api.V18.Geometry import NurbsData
from SpaceClaim.Api.V18.Geometry import NurbsSurface
from SpaceClaim.Api.V18.Geometry import OblongProfile
from SpaceClaim.Api.V18.Geometry import OffsetCornerType
from SpaceClaim.Api.V18.Geometry import Parameterization
from SpaceClaim.Api.V18.Geometry import ParamForm
from SpaceClaim.Api.V18.Geometry import PlacementUV
from SpaceClaim.Api.V18.Geometry import Plane
from SpaceClaim.Api.V18.Geometry import Point
from SpaceClaim.Api.V18.Geometry import PointCurve
from SpaceClaim.Api.V18.Geometry import PointF
from SpaceClaim.Api.V18.Geometry import PointUV
from SpaceClaim.Api.V18.Geometry import Polygon
from SpaceClaim.Api.V18.Geometry import PolygonProfile
from SpaceClaim.Api.V18.Geometry import PolylineOptions
from SpaceClaim.Api.V18.Geometry import ProceduralCurve
from SpaceClaim.Api.V18.Geometry import ProceduralSurface
from SpaceClaim.Api.V18.Geometry import Profile
from SpaceClaim.Api.V18.Geometry import RectangleProfile
from SpaceClaim.Api.V18.Geometry import RegularPolygonProfile
from SpaceClaim.Api.V18.Geometry import SelectFragmentResult
from SpaceClaim.Api.V18.Geometry import Separation
from SpaceClaim.Api.V18.Geometry import Space
from SpaceClaim.Api.V18.Geometry import Sphere
from SpaceClaim.Api.V18.Geometry import SquareProfile
from SpaceClaim.Api.V18.Geometry import StarProfile
from SpaceClaim.Api.V18.Geometry import Surface
from SpaceClaim.Api.V18.Geometry import SurfaceEvaluation
from SpaceClaim.Api.V18.Geometry import SurfaceSurfaceIntersection
from SpaceClaim.Api.V18.Geometry import Torus
from SpaceClaim.Api.V18.Geometry import Transformations
from SpaceClaim.Api.V18.Geometry import Vector
from SpaceClaim.Api.V18.Geometry import VectorUV
from SpaceClaim.Api.V18.Analysis import AssemblyMesh
from SpaceClaim.Api.V18.Analysis import BiasOption
from SpaceClaim.Api.V18.Analysis import BiasType
from SpaceClaim.Api.V18.Analysis import BlockingDecomposition
from SpaceClaim.Api.V18.Analysis import BodyMesh
from SpaceClaim.Api.V18.Analysis import EdgeElement
from SpaceClaim.Api.V18.Analysis import EdgeSizeControl
from SpaceClaim.Api.V18.Analysis import ElementShape
from SpaceClaim.Api.V18.Analysis import ElementType
from SpaceClaim.Api.V18.Analysis import FaceElement
from SpaceClaim.Api.V18.Analysis import FaceSizeControl
from SpaceClaim.Api.V18.Analysis import HexaBlocking
from SpaceClaim.Api.V18.Analysis import MeshBasedDefeaturing
from SpaceClaim.Api.V18.Analysis import MeshBodySettings
from SpaceClaim.Api.V18.Analysis import MeshMethods
from SpaceClaim.Api.V18.Analysis import MeshNode
from SpaceClaim.Api.V18.Analysis import MidsideNodes
from SpaceClaim.Api.V18.Analysis import PartMesh
from SpaceClaim.Api.V18.Analysis import PatchConformingTriangleSurfaceMesher
from SpaceClaim.Api.V18.Analysis import ProximityDirection
from SpaceClaim.Api.V18.Analysis import ProximitySizeFunctionSources
from SpaceClaim.Api.V18.Analysis import SizeFunction
from SpaceClaim.Api.V18.Analysis import VolumeElement
from SpaceClaim.Api.V18.Internal import AddInHelper
from SpaceClaim.Api.V18.Internal.AddInHelper import OnInitialized
from SpaceClaim.Api.V18.Internal.AddInHelper import Register
from SpaceClaim.Api.V18.Internal.AddInHelper import SetDefaultTool
from SpaceClaim.Api.V18.Internal import ControlCaddy
from SpaceClaim.Api.V18.Internal import ControlCaddyHelper
from SpaceClaim.Api.V18.Internal.ControlCaddyHelper import ToControl
from SpaceClaim.Api.V18.Internal import KeepAliveObjectRef
from SpaceClaim.Api.V18.Internal import NativeHandle
from SpaceClaim.Api.V18.Internal import Remoting
from SpaceClaim.Api.V18.Internal.Remoting import CreateRemoteObject
from SpaceClaim.Api.V18.Internal.Remoting import InitializeServer
from SpaceClaim.Api.V18.Internal.Remoting import RegisterClientType
from SpaceClaim.Api.V18.Internal.Remoting import RegisterSingleCall
from SpaceClaim.Api.V18.Internal import SessionManager

# SpaceClaim.Api.V18.Scripting types:
from SpaceClaim.Api.V18.Scripting import DocObjectHelper
from SpaceClaim.Api.V18.Scripting.DocObjectHelper import CreateWrapper
from SpaceClaim.Api.V18.Scripting.DocObjectHelper import RemoveWrapper
from SpaceClaim.Api.V18.Scripting import PersistenceMaps
from SpaceClaim.Api.V18.Scripting.PersistenceMaps import GetMaps
from SpaceClaim.Api.V18.Scripting import WrapperHelper
from SpaceClaim.Api.V18.Scripting.WrapperHelper import RemoveWrapper
from SpaceClaim.Api.V18.Scripting.PowerSelection import PowerSelection
from SpaceClaim.Api.V18.Scripting.PowerSelection import PowerSelectOptions
from SpaceClaim.Api.V18.Scripting.PowerSelection import RelationCategory
from SpaceClaim.Api.V18.Scripting.PowerSelection import RelationType
from SpaceClaim.Api.V18.Scripting.PowerSelection import SearchCriteria
from SpaceClaim.Api.V18.Scripting.PowerSelection import SearchCriteriaHelper
from SpaceClaim.Api.V18.Scripting.PowerSelection.SearchCriteriaHelper import GetExternal
from SpaceClaim.Api.V18.Scripting.PowerSelection.SearchCriteriaHelper import GetInternal
from SpaceClaim.Api.V18.Scripting.Selection import CurveSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import DatumLineSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import DatumPlaneSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import DatumPointSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import DesignAxisSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import EdgeSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import FaceSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import PointSelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import RayFire
from SpaceClaim.Api.V18.Scripting.Selection.RayFire import Fire
from SpaceClaim.Api.V18.Scripting.Selection import ScriptSelectionPointObject
from SpaceClaim.Api.V18.Scripting.Selection import Selection
from SpaceClaim.Api.V18.Scripting.Selection import SelectionPoint
from SpaceClaim.Api.V18.Scripting.Selection import SelectionType
from SpaceClaim.Api.V18.Scripting.ReplayBlocks import ReplayBlockHelper
from SpaceClaim.Api.V18.Scripting.Managers import ScriptEventManager
from SpaceClaim.Api.V18.Scripting.Helpers import AdjacentFacesInfo
from SpaceClaim.Api.V18.Scripting.Helpers import AngleBetweenObjectsInfo
from SpaceClaim.Api.V18.Scripting.Helpers import ApplicationHelper
from SpaceClaim.Api.V18.Scripting.Helpers import Beta
from SpaceClaim.Api.V18.Scripting.Helpers import BodyExtremaInfo
from SpaceClaim.Api.V18.Scripting.Helpers import ClosestResult
from SpaceClaim.Api.V18.Scripting.Helpers import ColorHelper
from SpaceClaim.Api.V18.Scripting.Helpers.ColorHelper import GetColor
from SpaceClaim.Api.V18.Scripting.Helpers.ColorHelper import SetColor
from SpaceClaim.Api.V18.Scripting.Helpers.ColorHelper import SetFillStyle
from SpaceClaim.Api.V18.Scripting.Helpers import ComponentHelper
from SpaceClaim.Api.V18.Scripting.Helpers import CurveCurveIntersectionResult
from SpaceClaim.Api.V18.Scripting.Helpers import CurveCurveIntersectionType
from SpaceClaim.Api.V18.Scripting.Helpers import CurveSurfaceIntersectionResult
from SpaceClaim.Api.V18.Scripting.Helpers import CurveSurfaceIntersectionType
from SpaceClaim.Api.V18.Scripting.Helpers import DialogResult
from SpaceClaim.Api.V18.Scripting.Helpers import DocumentHelper
from SpaceClaim.Api.V18.Scripting.Helpers.DocumentHelper import CloseDocument
from SpaceClaim.Api.V18.Scripting.Helpers.DocumentHelper import CreateNewDocument
from SpaceClaim.Api.V18.Scripting.Helpers.DocumentHelper import GetActiveDocument
from SpaceClaim.Api.V18.Scripting.Helpers.DocumentHelper import GetActivePart
from SpaceClaim.Api.V18.Scripting.Helpers.DocumentHelper import GetAllDocObjects
from SpaceClaim.Api.V18.Scripting.Helpers.DocumentHelper import GetRootPart
from SpaceClaim.Api.V18.Scripting.Helpers import FillStyle
from SpaceClaim.Api.V18.Scripting.Helpers import Gap
from SpaceClaim.Api.V18.Scripting.Helpers import GeometryHelper
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import CurveCurveIntersect
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import CurveSurfaceIntersection
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import GetDirectionFromSelection
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import GetPlaneFromSelection
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import GetPointFromSelection
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import PointSetClassification
from SpaceClaim.Api.V18.Scripting.Helpers.GeometryHelper import Rotate
from SpaceClaim.Api.V18.Scripting.Helpers import MeasureHelper
from SpaceClaim.Api.V18.Scripting.Helpers import MessageBox
from SpaceClaim.Api.V18.Scripting.Helpers.MessageBox import Show
from SpaceClaim.Api.V18.Scripting.Helpers import MessageBoxButtons
from SpaceClaim.Api.V18.Scripting.Helpers import MessageBoxIcon
from SpaceClaim.Api.V18.Scripting.Helpers import MidSurfaceBeamProperties
from SpaceClaim.Api.V18.Scripting.Helpers import MomentInfo
from SpaceClaim.Api.V18.Scripting.Helpers import NeighborhoodResult
from SpaceClaim.Api.V18.Scripting.Helpers import OpenFileDialog
from SpaceClaim.Api.V18.Scripting.Helpers import PointSetClassificationResult
from SpaceClaim.Api.V18.Scripting.Helpers import PointSetClassificationType
from SpaceClaim.Api.V18.Scripting.Helpers import ProjectedAreaInfo
from SpaceClaim.Api.V18.Scripting.Helpers import ProjectedGap
from SpaceClaim.Api.V18.Scripting.Helpers import SaveFileDialog
from SpaceClaim.Api.V18.Scripting.Helpers import ScriptObjectHelper
from SpaceClaim.Api.V18.Scripting.Helpers.ScriptObjectHelper import LoadReferencedObjects
from SpaceClaim.Api.V18.Scripting.Helpers.ScriptObjectHelper import LoadReferencedObjects_Legacy
from SpaceClaim.Api.V18.Scripting.Helpers.ScriptObjectHelper import LoadScriptObject
from SpaceClaim.Api.V18.Scripting.Helpers.ScriptObjectHelper import LoadScriptObject_Legacy
from SpaceClaim.Api.V18.Scripting.Helpers import SketchHelper
from SpaceClaim.Api.V18.Scripting.Helpers.SketchHelper import GetSketchLayout
from SpaceClaim.Api.V18.Scripting.Helpers.SketchHelper import SetConstructionCurve
from SpaceClaim.Api.V18.Scripting.Helpers.SketchHelper import SetMirrorLine
from SpaceClaim.Api.V18.Scripting.Helpers.SketchHelper import SetSketchLayout
from SpaceClaim.Api.V18.Scripting.Helpers.SketchHelper import StartConstraintSketching
from SpaceClaim.Api.V18.Scripting.Helpers import SketchState
from SpaceClaim.Api.V18.Scripting.Helpers import SpacePartition
from SpaceClaim.Api.V18.Scripting.Helpers import StatusMessage
from SpaceClaim.Api.V18.Scripting.Helpers import Units as Units1
from SpaceClaim.Api.V18.Scripting.Helpers.Units import CM
from SpaceClaim.Api.V18.Scripting.Helpers.Units import CM2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import CM3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import DEG
from SpaceClaim.Api.V18.Scripting.Helpers.Units import FT
from SpaceClaim.Api.V18.Scripting.Helpers.Units import FT2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import FT3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import IN
from SpaceClaim.Api.V18.Scripting.Helpers.Units import IN2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import IN3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import M
from SpaceClaim.Api.V18.Scripting.Helpers.Units import M2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import M3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import MIL
from SpaceClaim.Api.V18.Scripting.Helpers.Units import MIL2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import MIL3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import MM
from SpaceClaim.Api.V18.Scripting.Helpers.Units import MM2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import MM3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import NM
from SpaceClaim.Api.V18.Scripting.Helpers.Units import NM2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import NM3
from SpaceClaim.Api.V18.Scripting.Helpers.Units import PERCENT
from SpaceClaim.Api.V18.Scripting.Helpers.Units import RAD
from SpaceClaim.Api.V18.Scripting.Helpers.Units import UM
from SpaceClaim.Api.V18.Scripting.Helpers.Units import UM2
from SpaceClaim.Api.V18.Scripting.Helpers.Units import UM3
from SpaceClaim.Api.V18.Scripting.Helpers import UnitsHelper
from SpaceClaim.Api.V18.Scripting.Helpers.UnitsHelper import GetDocumentUnits
from SpaceClaim.Api.V18.Scripting.Helpers import ViewHelper
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import ActivateNamedView
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import CreateNamedView
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import GetCurrentProjection
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import GetObjectVisibility
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import GetSketchPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import GetViewMode
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import HideOthers
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import LockBodies
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetLastSectionPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetLastSketchPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetObjectVisibility
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetProjection
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetSectionPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetSketchPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetSuppressForPhysics
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import SetViewMode
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import ShowAll
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import TransformSketchPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import TransformSketchPlaneUpTo
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import TranslateSketchPlane
from SpaceClaim.Api.V18.Scripting.Helpers.ViewHelper import ZoomToEntity
from SpaceClaim.Api.V18.Scripting.Helpers import WindowHelper
from SpaceClaim.Api.V18.Scripting.Helpers.WindowHelper import GetGroups
from SpaceClaim.Api.V18.Scripting.Extensions import ComponentExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import DesignBodyExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import DesignCurveExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import DesignEdgeExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import DesignFaceExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import DesignMeshExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import DocObjectExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import HasNameExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import InternalExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import MidsurfaceAspectExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import PartDataType
from SpaceClaim.Api.V18.Scripting.Extensions import PartExtensions
from SpaceClaim.Api.V18.Scripting.Extensions import WireCurveExtensions
from SpaceClaim.Api.V18.Scripting.Commands import AdvancedForceShareTopology
from SpaceClaim.Api.V18.Scripting.Commands import Beam as Beam1
from SpaceClaim.Api.V18.Scripting.Commands.Beam import Create
from SpaceClaim.Api.V18.Scripting.Commands.Beam import ExtractProfile
from SpaceClaim.Api.V18.Scripting.Commands.Beam import GetExternal
from SpaceClaim.Api.V18.Scripting.Commands.Beam import GetInternal
from SpaceClaim.Api.V18.Scripting.Commands.Beam import GetProperty
from SpaceClaim.Api.V18.Scripting.Commands.Beam import ReverseBeam
from SpaceClaim.Api.V18.Scripting.Commands.Beam import SetOrientation
from SpaceClaim.Api.V18.Scripting.Commands.Beam import SetPosition
from SpaceClaim.Api.V18.Scripting.Commands.Beam import SetProfile
from SpaceClaim.Api.V18.Scripting.Commands.Beam import SetRigidity
from SpaceClaim.Api.V18.Scripting.Commands.Beam import SetType
from SpaceClaim.Api.V18.Scripting.Commands import BeamProfile
from SpaceClaim.Api.V18.Scripting.Commands import BeamProperty
from SpaceClaim.Api.V18.Scripting.Commands import BlockBody
from SpaceClaim.Api.V18.Scripting.Commands import CalculateProjectedArea
from SpaceClaim.Api.V18.Scripting.Commands import Chamfer
from SpaceClaim.Api.V18.Scripting.Commands import CircularSurface
from SpaceClaim.Api.V18.Scripting.Commands import ClosestPoint
from SpaceClaim.Api.V18.Scripting.Commands import Combine
from SpaceClaim.Api.V18.Scripting.Commands import CommandDataBase
from SpaceClaim.Api.V18.Scripting.Commands import ConstantRound
from SpaceClaim.Api.V18.Scripting.Commands import Constraint
from SpaceClaim.Api.V18.Scripting.Commands import ConstraintHelper
from SpaceClaim.Api.V18.Scripting.Commands import ConvertToSolid
from SpaceClaim.Api.V18.Scripting.Commands import Copy
from SpaceClaim.Api.V18.Scripting.Commands import CreationType
from SpaceClaim.Api.V18.Scripting.Commands import CrossSectionItemType
from SpaceClaim.Api.V18.Scripting.Commands import Cut
from SpaceClaim.Api.V18.Scripting.Commands import CylinderBody
from SpaceClaim.Api.V18.Scripting.Commands import DatumLineCreator
from SpaceClaim.Api.V18.Scripting.Commands import DatumOriginCreator
from SpaceClaim.Api.V18.Scripting.Commands import DatumPlaneCreator
from SpaceClaim.Api.V18.Scripting.Commands import DatumPointCreator
from SpaceClaim.Api.V18.Scripting.Commands import Delete
from SpaceClaim.Api.V18.Scripting.Commands import DetachFaces
from SpaceClaim.Api.V18.Scripting.Commands import Dimension
from SpaceClaim.Api.V18.Scripting.Commands import DocumentInsert
from SpaceClaim.Api.V18.Scripting.Commands import DocumentOpen
from SpaceClaim.Api.V18.Scripting.Commands import DocumentSave
from SpaceClaim.Api.V18.Scripting.Commands import DraftFaces
from SpaceClaim.Api.V18.Scripting.Commands import DraftSide
from SpaceClaim.Api.V18.Scripting.Commands import DuplicateCurveProblemArea
from SpaceClaim.Api.V18.Scripting.Commands import Enclosure
from SpaceClaim.Api.V18.Scripting.Commands import ExtrudeEdges
from SpaceClaim.Api.V18.Scripting.Commands import ExtrudeFaces
from SpaceClaim.Api.V18.Scripting.Commands import ExtrudeProfile
from SpaceClaim.Api.V18.Scripting.Commands import FacetAutoFix
from SpaceClaim.Api.V18.Scripting.Commands import FacetConvert
from SpaceClaim.Api.V18.Scripting.Commands import FacetCreate
from SpaceClaim.Api.V18.Scripting.Commands import FacetFixHoles
from SpaceClaim.Api.V18.Scripting.Commands import FacetFixIntersections
from SpaceClaim.Api.V18.Scripting.Commands import FacetFixOverConnections
from SpaceClaim.Api.V18.Scripting.Commands import FacetFixSharps
from SpaceClaim.Api.V18.Scripting.Commands import FacetIntersect
from SpaceClaim.Api.V18.Scripting.Commands import FacetJoin
from SpaceClaim.Api.V18.Scripting.Commands import FacetMerge
from SpaceClaim.Api.V18.Scripting.Commands import FacetReduce
from SpaceClaim.Api.V18.Scripting.Commands import FacetRemesh
from SpaceClaim.Api.V18.Scripting.Commands import FacetSelectBySourceGeometry
from SpaceClaim.Api.V18.Scripting.Commands import FacetSeparate
from SpaceClaim.Api.V18.Scripting.Commands import FacetShell
from SpaceClaim.Api.V18.Scripting.Commands import FacetSmooth
from SpaceClaim.Api.V18.Scripting.Commands import FacetSplit
from SpaceClaim.Api.V18.Scripting.Commands import FacetSubtract
from SpaceClaim.Api.V18.Scripting.Commands import FacetThicken
from SpaceClaim.Api.V18.Scripting.Commands import FileType
from SpaceClaim.Api.V18.Scripting.Commands import Fill
from SpaceClaim.Api.V18.Scripting.Commands import FillMode
from SpaceClaim.Api.V18.Scripting.Commands import FixCommand
from SpaceClaim.Api.V18.Scripting.Commands import FixCurveCommand
from SpaceClaim.Api.V18.Scripting.Commands import FixCurveGaps
from SpaceClaim.Api.V18.Scripting.Commands import FixDuplicateCurves
from SpaceClaim.Api.V18.Scripting.Commands import FixDuplicateFaces
from SpaceClaim.Api.V18.Scripting.Commands import FixExtendableSurfaces
from SpaceClaim.Api.V18.Scripting.Commands import FixExtraEdges
from SpaceClaim.Api.V18.Scripting.Commands import FixGaps
from SpaceClaim.Api.V18.Scripting.Commands import FixIdentifyIcepakObjects
from SpaceClaim.Api.V18.Scripting.Commands import FixImprint
from SpaceClaim.Api.V18.Scripting.Commands import FixInterference
from SpaceClaim.Api.V18.Scripting.Commands import FixMissingFaces
from SpaceClaim.Api.V18.Scripting.Commands import FixShortEdges
from SpaceClaim.Api.V18.Scripting.Commands import FixSmallFaces
from SpaceClaim.Api.V18.Scripting.Commands import FixSplitEdges
from SpaceClaim.Api.V18.Scripting.Commands import ForceShareTopology
from SpaceClaim.Api.V18.Scripting.Commands import FullRound
from SpaceClaim.Api.V18.Scripting.Commands import HandleAxis
from SpaceClaim.Api.V18.Scripting.Commands import HoleDepthMeasurementType as HoleDepthMeasurementType1
from SpaceClaim.Api.V18.Scripting.Commands import HoleFit as HoleFit1
from SpaceClaim.Api.V18.Scripting.Commands import HoleLocation
from SpaceClaim.Api.V18.Scripting.Commands import IcepakEnclosure
from SpaceClaim.Api.V18.Scripting.Commands import IcepakFan
from SpaceClaim.Api.V18.Scripting.Commands import IcepakGrille
from SpaceClaim.Api.V18.Scripting.Commands import IcepakOpening
from SpaceClaim.Api.V18.Scripting.Commands import IcepakSimplify
from SpaceClaim.Api.V18.Scripting.Commands import IcepakViewHelper
from SpaceClaim.Api.V18.Scripting.Commands import IdentifiedHole
from SpaceClaim.Api.V18.Scripting.Commands import IntersectionType
from SpaceClaim.Api.V18.Scripting.Commands import Layers
from SpaceClaim.Api.V18.Scripting.Commands import Loft
from SpaceClaim.Api.V18.Scripting.Commands import MergeBodies
from SpaceClaim.Api.V18.Scripting.Commands import Midsurface
from SpaceClaim.Api.V18.Scripting.Commands import MidsurfaceOffsetFaces
from SpaceClaim.Api.V18.Scripting.Commands import Mirror
from SpaceClaim.Api.V18.Scripting.Commands import MirrorComponents
from SpaceClaim.Api.V18.Scripting.Commands import MirrorFaces
from SpaceClaim.Api.V18.Scripting.Commands import Move
from SpaceClaim.Api.V18.Scripting.Commands import MoveImprintEdges
from SpaceClaim.Api.V18.Scripting.Commands import MoveSketchCurve
from SpaceClaim.Api.V18.Scripting.Commands import NamedSelection
from SpaceClaim.Api.V18.Scripting.Commands import OffsetEdges
from SpaceClaim.Api.V18.Scripting.Commands import OffsetFaceCurves
from SpaceClaim.Api.V18.Scripting.Commands import OffsetFaces
from SpaceClaim.Api.V18.Scripting.Commands import OffsetRelation
from SpaceClaim.Api.V18.Scripting.Commands import PartLocation
from SpaceClaim.Api.V18.Scripting.Commands import Paste
from SpaceClaim.Api.V18.Scripting.Commands import Pattern
from SpaceClaim.Api.V18.Scripting.Commands import PlanarBody
from SpaceClaim.Api.V18.Scripting.Commands import Point2D
from SpaceClaim.Api.V18.Scripting.Commands import PointDesignObjectPair
from SpaceClaim.Api.V18.Scripting.Commands import ProjectToSketch
from SpaceClaim.Api.V18.Scripting.Commands import ProjectToSolid
from SpaceClaim.Api.V18.Scripting.Commands import PullCurvePoint
from SpaceClaim.Api.V18.Scripting.Commands import RectangularSurface
from SpaceClaim.Api.V18.Scripting.Commands import RenameObject
from SpaceClaim.Api.V18.Scripting.Commands import ReplaceFacesWithFace
from SpaceClaim.Api.V18.Scripting.Commands import RevolveEdges
from SpaceClaim.Api.V18.Scripting.Commands import RevolveFaces
from SpaceClaim.Api.V18.Scripting.Commands import RevolvePoints
from SpaceClaim.Api.V18.Scripting.Commands import RoundInfo
from SpaceClaim.Api.V18.Scripting.Commands import Scale
from SpaceClaim.Api.V18.Scripting.Commands import ScaleSketchCurve
from SpaceClaim.Api.V18.Scripting.Commands import SharePrep
from SpaceClaim.Api.V18.Scripting.Commands import ShareTopology as ShareTopology1
from SpaceClaim.Api.V18.Scripting.Commands import Shell
from SpaceClaim.Api.V18.Scripting.Commands import Shrinkwrap
from SpaceClaim.Api.V18.Scripting.Commands import Sketch2DRound
from SpaceClaim.Api.V18.Scripting.Commands import SketchArc
from SpaceClaim.Api.V18.Scripting.Commands import SketchCircle
from SpaceClaim.Api.V18.Scripting.Commands import SketchCorner
from SpaceClaim.Api.V18.Scripting.Commands import SketchCurve
from SpaceClaim.Api.V18.Scripting.Commands import SketchEllipse
from SpaceClaim.Api.V18.Scripting.Commands import SketchLine
from SpaceClaim.Api.V18.Scripting.Commands import SketchNurbs
from SpaceClaim.Api.V18.Scripting.Commands import SketchOffsetCurve
from SpaceClaim.Api.V18.Scripting.Commands import SketchOnSolid
from SpaceClaim.Api.V18.Scripting.Commands import SketchPlane
from SpaceClaim.Api.V18.Scripting.Commands import SketchPoint
from SpaceClaim.Api.V18.Scripting.Commands import SketchPolygon
from SpaceClaim.Api.V18.Scripting.Commands import SketchRectangle
from SpaceClaim.Api.V18.Scripting.Commands import SkinFromFacetHeightField
from SpaceClaim.Api.V18.Scripting.Commands import SphereBody
from SpaceClaim.Api.V18.Scripting.Commands import SplitBody
from SpaceClaim.Api.V18.Scripting.Commands import SplitEdge
from SpaceClaim.Api.V18.Scripting.Commands import SplitFace
from SpaceClaim.Api.V18.Scripting.Commands import SplitRound
from SpaceClaim.Api.V18.Scripting.Commands import SplitSketchCurve
from SpaceClaim.Api.V18.Scripting.Commands import StandardHoles
from SpaceClaim.Api.V18.Scripting.Commands import StitchFaces
from SpaceClaim.Api.V18.Scripting.Commands import STLFile
from SpaceClaim.Api.V18.Scripting.Commands import SurfaceBody
from SpaceClaim.Api.V18.Scripting.Commands import Sweep
from SpaceClaim.Api.V18.Scripting.Commands import SweepPoints
from SpaceClaim.Api.V18.Scripting.Commands import ThickenFaces
from SpaceClaim.Api.V18.Scripting.Commands import TransformType
from SpaceClaim.Api.V18.Scripting.Commands import TrimSketchCurve
from SpaceClaim.Api.V18.Scripting.Commands import TubeBody
from SpaceClaim.Api.V18.Scripting.Commands import UnShareTopology
from SpaceClaim.Api.V18.Scripting.Commands import VisibilityType
from SpaceClaim.Api.V18.Scripting.Commands import VolumeExtract
from SpaceClaim.Api.V18.Scripting.Commands import WorkingField
from SpaceClaim.Api.V18.Scripting.Commands import Workpiece
from SpaceClaim.Api.V18.Scripting.Commands import Wrap
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import BeamConnectionProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import BeamSplitProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CoincidentBeamVertexInfo
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CoincidentBeamVertexProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CoincidentEdgeInfo
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CoincidentEdgeProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CoincidentFaceInfo
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CoincidentFaceProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import CurveGapProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import InternalBaffleInfo
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import InternalBaffleProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import ProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.ProblemAreas import SplitEdgeProblemArea
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import CircularPatternData
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import CircularPatternModificationData
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import FillPatternData
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import FillPatternType
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import LinearPatternData
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import LinearPatternModificationData
from SpaceClaim.Api.V18.Scripting.Commands.CommandData import PatternDimensionType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ArcSense
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import Axis
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import AxisCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import BaselineOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import BeamSplitsOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import BoxEnclosureCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import BoxWorkpieceCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ChamferOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import CombineOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import CommandOptionsBase
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ConstantRoundOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import CreationLocation
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import CylinderEnclosureCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import CylinderWorkpieceCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import DimensionAlignment
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import DimensionSpan
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import DraftOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import EdgeCategoryToProject
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import EdgeColorTarget
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import EnclosureOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import EnclosureType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ExportFormatType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ExtrudeEdgeOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ExtrudeFaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ExtrudeType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FaceColorTarget
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FaceEdgeSplitter
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FaceSplitType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetConvertOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetFixHolesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetFixSharpsOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetIntersectOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetMergeOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetQuality
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetReduceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetRemeshOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetSeparateOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetShellOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetSmoothOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetSplitOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetSubtractOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FacetThickenOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FillOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FillRelationship
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FillType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FindConvexConcaveOption
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FindStandardHoleOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FindVerticesEdgesOption
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixBeamConnectionsOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixCurveGapsOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixDuplicateFacesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixExtendableSurfacesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixGapsOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixIdentifyIcepakOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixImprintOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixInterferenceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixMethodsType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixMissingFacesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixShortEdgesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixSmallFacesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import FixSplitEdgesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import GeometryCommandOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakEnclosureOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakGeometryTypes
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakGrilleOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakGrilleType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakObjectsType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakSimplifyLevelOneOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakSimplifyLevelTwoOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import IcepakSimplifyLevelZeroOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import LengthUnits
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import LoftOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MakeCurvesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MakeSolidsOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MergeBodiesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MeshInfillType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MidsurfaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MirrorOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ModificationOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MoveImprintEdgeMode
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MoveImprintEdgeOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import MoveOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import OffsetCurveGapType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import OffsetFaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import OffsetMode
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ProjectToSketchOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ProjectToSolidOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import PullCurvePointOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import PullMode
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ReplaceFacesWithFaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import RevolveFaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SetColorOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SharePrepOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ShareTopologyOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ShrinkwrapOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import Sketch2DRoundOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchArcOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchCircleOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchCornerOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchEllipseOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchOffsetOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchOnSolidOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SketchPolygonOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SmoothType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SphereEnclosureCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SphereWorkpieceCushion
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SplitFaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SplitterType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import StandardHolesOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import StitchOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import STLExportOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import StlImportExportOptionsHelper
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import STLImportOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import StlInputOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import StlOutputOption
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import StlResolutionType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SweepCommandOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import SweepPointCommandOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ThickenDirection
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import ThickenFaceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import TrimSketchCurveOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import VolumeExtractOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import WorkpieceOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import WorkpieceType
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import WrapDirections
from SpaceClaim.Api.V18.Scripting.Commands.CommandOptions import WrapOptions
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import BeamResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import BeamSplitsResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import BlockBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CalculateProjectedAreaResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ChamferResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CircularSurfaceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ClosestPointCurveResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ClosestPointResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ClosestPointSurfaceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CombineResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ComponentCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ConstantRoundResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ConvertStandardHolesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ConvertToSolidResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CreateBeamProfileResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CreateNamedSelectionGroupResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CreateStandardHolesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import CylinderBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import DatumLineResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import DatumOriginResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import DatumPlaneResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import DatumPointResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import DetachFacesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import DraftFacesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import EnclosureResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ExtractBeamResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ExtrudeEdgesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ExtrudeFacesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ExtrudeSolidBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetAutoFixResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetConvertResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetCreateResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetFixHolesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetFixIntersectionsResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetFixOverConnectionsResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetFixSharpsResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetIntersectResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetJoinResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetMergeResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetReduceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetRemeshResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetSeparateResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetShellResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetSmoothResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetSplitResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetSubtractResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FacetThickenResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FillResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FixCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import FullRoundResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import IcepakEnclosureResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import IcepakFanResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import IcepakGrilleResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import IcepakOpeningResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import IcepakSimplifyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ImprintEdgesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import LoftResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import MergeBodiesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import MidsurfaceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import MirrorCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import MirrorComponentsCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import MirrorFacesCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ModifyStandardHolesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import MoveResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import NewLayerResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import OffsetEdgesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import OffsetFaceCurvesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import OffsetFacesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import PasteResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import PatternResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import PauseAndGetInputResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import PlanarBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ProjectToSolidResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import PullCurvePointCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import RectangularSurfaceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import RemoveStandardHoleAssociationsResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ReplaceFacesWithFaceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ReverseStandardHolesCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import RevolveCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import RevolveEdgesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import RevolvePointsCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import RoundInfoResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SetViewModeCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SharePrepResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ShellResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ShrinkwrapResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SketchCurveResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SphereResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SplitBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SplitEdgeResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SplitFaceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SplitRoundResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SurfaceBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SweepCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import SweepPointsCommandResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import ThickenFacesResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import TubeBodyResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import VolumeExtractResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import WorkpieceResult
from SpaceClaim.Api.V18.Scripting.Commands.CommandResults import WrapResult


clr.ImportExtensions(ComponentExtensions)
clr.ImportExtensions(DesignBodyExtensions)
clr.ImportExtensions(DesignCurveExtensions)
clr.ImportExtensions(DesignEdgeExtensions)
clr.ImportExtensions(DesignFaceExtensions)
clr.ImportExtensions(DesignMeshExtensions)
clr.ImportExtensions(DocObjectExtensions)
clr.ImportExtensions(HasNameExtensions)
clr.ImportExtensions(InternalExtensions)
clr.ImportExtensions(MidsurfaceAspectExtensions)
clr.ImportExtensions(PartExtensions)
clr.ImportExtensions(WireCurveExtensions)
